<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CleanArchitectureMvc.Infra.IoC\CleanArchitectureMvc.Infra.IoC.csproj"/>
    </ItemGroup>

</Project>
